---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mautic
  labels:
    app: {{ .Release.Name }}-mautic
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mautic
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mautic
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mautic
  serviceName: "{{ .Release.Name }}-mariadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mautic
    spec:
      containers:
      - name: {{ .Release.Name }}-mautic
        image: "{{ .Values.mautic.image.name }}:{{ .Values.mautic.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: MAUTIC_INSTALL_FORCE
          value: "true"
        - name: MAUTIC_RUN_CRON_JOBS
          value: "true"
        - name: MAUTIC_URL
          value: http://{{ .Release.Name }}.stimch.com
        - name: MAUTIC_ADMIN_EMAIL
          value: {{ .Values.mautic.admin.email | quote }}
        - name: MAUTIC_ADMIN_USERNAME
          value: {{ .Values.mautic.admin.username | quote }}
        - name: MAUTIC_ADMIN_FIRSTNAME
          value: {{ .Values.mautic.admin.firstname | quote }}
        - name: MAUTIC_ADMIN_LASTNAME
          value: {{ .Values.mautic.admin.lastname | quote }}
        - name: MAUTIC_ADMIN_PASSWORD
          value: {{ .Values.mautic.admin.password | quote }}
        - name: MAUTIC_DB_HOST
          value: "{{ .Release.Name }}-mariadb:3306"
        - name: MAUTIC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mariadb-secret
              key: password
        - name: MAUTIC_CONFIG_MAILER_TRANSPORT
          value: {{ .Values.mautic.mailer.transport }}
        - name: MAUTIC_CONFIG_MAILER_HOST
          value: {{ .Values.mautic.mailer.host }}
        - name: MAUTIC_CONFIG_MAILER_PORT
          value: {{ .Values.mautic.mailer.port | quote }}
        - name: MAUTIC_CONFIG_MAILER_FROM_EMAIL
          value: {{ .Values.mautic.mailer.from_email }}
        - name: MAUTIC_CONFIG_SAML_IDP_ENTITY_ID
          value: http://{{ .Release.Name }}.stimch.com
        - name: MAUTIC_CONFIG_SAML_IDP_EMAIL_ATTRIBUTE
          value: EmailAddress
        - name: MAUTIC_CONFIG_SAML_IDP_FIRSTNAME_ATTRIBUTE
          value: FirstName
        - name: MAUTIC_CONFIG_SAML_IDP_LASTNAME_ATTRIBUTE
          value: LastName
        - name: MAUTIC_CONFIG_SAML_IDP_DEFAULT_ROLE
          value: "1"
        - name: MAUTIC_CONFIG_SAML_IDP_METADATA
          value: {{ .Values.mautic.saml.metadata }}
        - name: MAUTIC_CONFIG_SAML_IDP_OWN_CERTIFICATE
          value: {{ .Values.mautic.saml.certificate }}
        - name: MAUTIC_CONFIG_SAML_IDP_OWN_PRIVATE_KEY
          value: {{ .Values.mautic.saml.private_key }}
        - name: MAUTIC_CONFIG_API_ENABLED
          value: "1"
        - name: MAUTIC_CONFIG_API_ENABLE_BASIC_AUTH
          value: "true"

        volumeMounts:
        - name: {{ .Release.Name }}-mautic-persistent-storage
          mountPath: "/var/www/html"
        resources:
          limits:
            cpu: {{ .Values.mautic.resources.limits.cpu }}
            memory: {{ .Values.mautic.resources.limits.memory }}
          requests:
            cpu: {{ .Values.mautic.resources.requests.cpu }}
            memory: {{ .Values.mautic.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /s/login
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 3
          timeoutSeconds: 5

      volumes:
      - name: {{ .Release.Name }}-mautic-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mautic-pvc
